### PR TITLE
Fixed vspaces in cover and title

### PR DESCRIPTION
**Pull request by MoritzS**
\vspace is ignored at the start of the page, \vspace* must be used
instead.
Since the space was ignored, I removed it from the title and reduced it on the cover to center the page.

### CODE REVIEW

**Comment by fwalch** [comment]
Thanks for noticing this! I'm not sure if I like the shift between cover and title page, though.. what about just removing the \vspace on both pages?

**Comment by MoritzS** [comment]
Ultimately that's a matter of taste and it's easy to adjust it the way you want.

If you prefer I'll remove the space in the cover.

**Comment by fwalch** [comment]
> If you prefer I'll remove the space in the cover.

Yes, please :-)

**Comment by MoritzS** [comment]
Done.

**Comment by fwalch** [comment]
Thanks!

**Pull request merged**
